### ISSUE TITLE
Two Questions

### ISSUE THREAD

**Issue by 66Kevin** [zcablii/RS_detection#5]
Hi all,
Thanks for your amazing work!
我有几个问题想询问一下，
1. 你们为什么要特意将数据集中分辨率大于2,500 * 2500 的进行灰度化处理呢？这样做有什么好处以及这样做带来了多少百分点的提升？
2. 使用VAN backbone大概能带来多少百分点的提升？
3. 使用三个尺度0.5,1.0,1.5的训练时间大概多久？

Best wishes,
Yueyi Wang

**Comment by zcablii** [comment]
1. 本次比赛中的数据集中有灰度图，我们按照灰图样本的分布来进行灰度化处理。若扩充数据集不进行灰度化处理，会掉约3.5%mAP
2. 在验证集上，res101：0.7898， res152：0.8073，van_b3：**0.8480**。
3. 多尺寸的训练集大约有194k张图像，8卡3090需要训大概60小时。
更多具体的细节和结果可以参考我们的答辩PPT：https://liveuclac-my.sharepoint.com/:p:/g/personal/zcablii_ucl_ac_uk/EUfj2wJf1aNLhP4jSYrznBgBqOKvD-o-wx8LPIQ_4vARHQ?e=ItEYVK
