### ISSUE TITLE
能解释一下为什么采用这种图片预处理的方式吗？

### ISSUE THREAD

**Issue by jsxyhelu** [zcablii/RS_detection#7]
我指的是“FAIR1M2.0 数据集包含train， validation 和 test集，我们将有标签的train和validation合并，并命名为train_color，并将数据集中分辨率大于2,500 * 2500 的进行灰度化处理，并将灰度化的副本单独存放为train_gray用于后续处理。”
感谢！

**Comment by zcablii** [comment]
Please refer to [https://github.com/zcablii/RS_detection/issues/5](url)

**Comment by zcablii** [comment]
Please refer to #5
