### ISSUE TITLE
One Question

### ISSUE THREAD

**Issue by BeiYining** [zcablii/RS_detection#9]
Dear Li,
Thanks for your excellent work!
您提出的LSKNet在code中有tiny和small的实现，我想请问一下，您有做过增大backbone量级的工作吗，比如lsk-m，lsk-l，甚至lsk-x，或者说您做过但是其精度和速度不够理想呢？
Best wishes,
Shuo Yang

**Comment by zcablii** [comment]
I attempted to use the LSK-M model, but found that its performance was similar to that of LSK-S, while requiring more computational resources. Therefore, we have decided to only release LSK-T for efficiency and LSK-S for performance.  We have observed a similar phenomenon in the Oriented-RCNN framework when using the Resnet backbone. Specifically, Res101 is not as comparable to Res50 in terms of performance. It is possible that overfitting occurs when using a larger capacity backbone, as the increased number of parameters may lead to overfitting on smaller datasets. 

BTW, for discussing about LSK (Large selective network), please go to this repo: [https://github.com/zcablii/Large-Selective-Kernel-Network](url)

**Comment by BeiYining** [comment]
I see, thanks for your reply.
